### ISSUE TITLE
Fix 404 links

### ISSUE THREAD

**Issue by p55** [BookingSync/bookingsync-websites-docs#9]
All links from the list on http://website.docs.bookingsync.com/reference/tags/ leads to 404 pages. For example:
`1. Control Flow Tags` links to http://website.docs.bookingsync.com/tags/control_flow_tags/
`2. Iteration Tags` links to http://website.docs.bookingsync.com/tags/iteration_tags/

**Comment by hash4di** [comment]
Closed by https://github.com/BookingSync/bookingsync-websites-docs/pull/10
